# site settings
title: Prateek
subtitle: 
email: prateekpunetha@gmail.com
description: An Android and Linux Enthusiast 
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Prateek
street_address: 
city: Pithoragarh
state: Uttarakhand
zip_code: 262501
country: India
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/PrateekPunetha
telegram_url: https://t.me/prateekpunetha
xda_url: https://forum.xda-developers.com/member.php?u=9362058

# build settings
markdown: kramdown

sass:
  style: compressed
